import "public/globals.css";
import Navbar from "./navbar";
import { Ubuntu } from "next/font/google";
export const metadata = {
  title: "SafoMart",
  description: "Generated by Next.js",
};
const mooli = Ubuntu({
  weight: ["400", "300", "500", "700"],
  subsets: ["latin"],
  style: ["normal"],
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={mooli.className}>
        <div className="container mx-auto">
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
